### ISSUE TITLE
Custom installer name?

### ISSUE THREAD

**Issue by Snaid1** [azuravian/playnite-LocalInstallButton#1]
I am trying to install an old game I made an ISO of and the setup file on the iso is a different name than what you'd usually find. Is there any way to pass in an alternate name to run when clicking install?

current behavior is I click install, the button changes to say "installing" but nothing happens.

**Comment by azuravian** [comment]
Let me see if I can put in a check.  If no setup.exe is found in the ISO, it will then prompt for the file.

**Comment by Snaid1** [comment]
that works for me! thanks! I tried seeing if I could modify the code to scrape the autorun.inf file for the setup file but it turns out piping powershell commands and turning the results into a string are harder than I initially thought.
