### ISSUE TITLE
[Enhancement] Add the option to browse for installed game.exe instead of installing. 

### ISSUE THREAD

**Issue by Overload86** [azuravian/playnite-LocalInstallButton#4]
Would it be possible to either have a third option after "Select image/folder" and "Select setup.exe" to just go "Select game executable instead?"
Alternatively make the first popup "There is no install action defined, would you like to install now or manually browse for the executable?"
Bonus Points if you could drag and drop a exe or shortcut directly onto the install button or the popup window and just fill out "Install folder", "play action" and the `installed` flag.

**Comment by azuravian** [comment]
Fixed in 1.3
