### ISSUE TITLE
Issue with Open Dialog

### ISSUE THREAD

**Issue by Kyzoku** [azuravian/playnite-LocalInstallButton#6]
After I install or cancel the installer, the open dialog shows up again.  Is there any way to stop this from happening?

**Comment by azuravian** [comment]
The second Open Dialog is there to point to the installation location after install.  This way the plugin can create a new Play action and add it to the Game in Playnite.

**Comment by Kyzoku** [comment]
I see, thank you for clarifying that for me.

**Comment by Kyzoku** [comment]
Coming back to this, would it be possible to disable the Open Dialog if the game already has a Play Action or at least make it an option?
