### ISSUE TITLE
Install file must be "setup.exe" as it's not recognized otherwise

### ISSUE THREAD

**Issue by Nightchanger** [azuravian/playnite-LocalInstallButton#8]
Install file from immortal darkness is "Immortal Darkness Curse of The Pale King (V1.0.0.121822f).exe" And so it's not the standard.
Should be tested on https://immortaldarkness.com/ as they give the game for free.

**Comment by azuravian** [comment]
Just tested and this is working for me.

When you add a "ROM" in Playnite under Installation, what is it pointing to?  It should point to the actual executable as opposed to just the folder.

**Comment by azuravian** [comment]
Closed as resolved
